### ISSUE TITLE
Combine with nacho?

### ISSUE THREAD

**Issue by mapsam** [mapbox/ecs-telephone#2]
[Nacho](https://github.com/mapbox/nacho) was my original foray into watchbot, but that was prior to ecs-watchbot. Converting that into ecs-watchbot would make it the same thing as this repository. I'd be happy to write up a little "how to spin this up" in the readme, like Nacho.

Can we join forces? It's always [better when we're together](https://www.youtube.com/watch?v=u57d4_b_YgI). 

@rclark @jakepruitt

**Comment by rclark** [comment]
Do you mean adding "how to spin this up" to this repo's readme? I think that'd be awesome!

**Comment by mapsam** [comment]
Cool! I'll do that - but also what does this telephone do? Does it just log the message sent?

**Comment by rclark** [comment]
Have you ever played "Telephone"? Where one person whispers something in the next person's ear, and the next, and the next, and by the end the message is all scrambled?

Well that's what this does. Receives a message, randomly replaces one of the words in it, and then sends the new message back to the queue.

**Comment by mapsam** [comment]
I have! So it never stops until you stop it, yeah?

**Comment by rclark** [comment]
Yes, it never stops, and yes, I've just sent the messages manually in the past. In the end I walked away with a few decent new band names.

**Comment by mapsam** [comment]
Posting this for posterity - and for use in the README

![screen shot 2017-06-21 at 5 48 49 pm](https://user-images.githubusercontent.com/1943001/27412508-f6b79500-56a9-11e7-8e03-6c881fe45748.png)
